export const formasDePago = {
  '01': 'Efectivo',
  '02': 'Cheque nominativo',
  '03': 'Transferencia electrónica de fondos',
  '04': 'Tarjeta de crédito',
  '05': 'Monedero electrónico',
  '06': 'Dinero electrónico',
  '08': 'Vales de despensa',
  12: 'Dación en pago',
  13: 'Pago por subrogación',
  14: 'Pago por consignación',
  15: 'Condonación',
  17: 'Compensación',
  23: 'Novación',
  24: 'Confusión',
  25: 'Remisión de deuda',
  26: 'Prescripción o caducidad',
  27: 'A satisfacción del acreedor',
  28: 'Tarjeta de débito',
  29: 'Tarjeta de servicios',
  30: 'Aplicación de anticipos',
  31: 'Intermediario pagos',
  99: 'Por definir',
};

export const metodosDePago = {
  PUE: 'Pago en una sola exhibición',
  PPD: 'Pago en parcialidades o diferido',
};

export const tiposDeMoneda = {
  AED: 'Dirham de EAU',
  AFN: 'Afghani',
  ALL: 'Lek',
  AMD: 'Dram armenio',
  ANG: 'Florín antillano neerlandés',
  AOA: 'Kwanza',
  ARS: 'Peso Argentino',
  AUD: 'Dólar Australiano',
  AWG: 'Aruba Florin',
  AZN: 'Azerbaijanian Manat',
  BAM: 'Convertibles marca',
  BBD: 'Dólar de Barbados',
  BDT: 'Taka',
  BGN: 'Lev búlgaro',
  BHD: 'Dinar de Bahrein',
  BIF: 'Burundi Franc',
  BMD: 'Dólar de Bermudas',
  BND: 'Dólar de Brunei',
  BOB: 'Boliviano',
  BOV: 'Mvdol',
  BRL: 'Real brasileño',
  BSD: 'Dólar de las Bahamas',
  BTN: 'Ngultrum',
  BWP: 'Pula',
  BYR: 'Rublo bielorruso',
  BZD: 'Dólar de Belice',
  CAD: 'Dolar Canadiense',
  CDF: 'Franco congoleño',
  CHE: 'WIR Euro',
  CHF: 'Franco Suizo',
  CHW: 'Franc WIR',
  CLF: 'Unidad de Fomento',
  CLP: 'Peso chileno',
  CNY: 'Yuan Renminbi',
  COP: 'Peso Colombiano',
  COU: 'Unidad de Valor real',
  CRC: 'Colón costarricense',
  CUC: 'Peso Convertible',
  CUP: 'Peso Cubano',
  CVE: 'Cabo Verde Escudo',
  CZK: 'Corona checa',
  DJF: 'Franco de Djibouti',
  DKK: 'Corona danesa',
  DOP: 'Peso Dominicano',
  DZD: 'Dinar argelino',
  EGP: 'Libra egipcia',
  ERN: 'Nakfa',
  ETB: 'Birr etíope',
  EUR: 'Euro',
  FJD: 'Dólar de Fiji',
  FKP: 'Libra malvinense',
  GBP: 'Libra Esterlina',
  GEL: 'Lari',
  GHS: 'Cedi de Ghana',
  GIP: 'Libra de Gibraltar',
  GMD: 'Dalasi',
  GNF: 'Franco guineano',
  GTQ: 'Quetzal',
  GYD: 'Dólar guyanés',
  HKD: 'Dolar De Hong Kong',
  HNL: 'Lempira',
  HRK: 'Kuna',
  HTG: 'Gourde',
  HUF: 'Florín',
  IDR: 'Rupia',
  ILS: 'Nuevo Shekel Israelí',
  INR: 'Rupia india',
  IQD: 'Dinar iraquí',
  IRR: 'Rial iraní',
  ISK: 'Corona islandesa',
  JMD: 'Dólar Jamaiquino',
  JOD: 'Dinar jordano',
  JPY: 'Yen',
  KES: 'Chelín keniano',
  KGS: 'Som',
  KHR: 'Riel',
  KMF: 'Franco Comoro',
  KPW: 'Corea del Norte ganó',
  KRW: 'Won',
  KWD: 'Dinar kuwaití',
  KYD: 'Dólar de las Islas Caimán',
  KZT: 'Tenge',
  LAK: 'Kip',
  LBP: 'Libra libanesa',
  LKR: 'Rupia de Sri Lanka',
  LRD: 'Dólar liberiano',
  LSL: 'Loti',
  LYD: 'Dinar libio',
  MAD: 'Dirham marroquí',
  MDL: 'Leu moldavo',
  MGA: 'Ariary malgache',
  MKD: 'Denar',
  MMK: 'Kyat',
  MNT: 'Tugrik',
  MOP: 'Pataca',
  MRO: 'Ouguiya',
  MUR: 'Rupia de Mauricio',
  MVR: 'Rupia',
  MWK: 'Kwacha',
  MXN: 'Peso Mexicano',
  MXV: 'México Unidad de Inversión (UDI',
  MYR: 'Ringgit malayo',
  MZN: 'Mozambique Metical',
  NAD: 'Dólar de Namibia',
  NGN: 'Naira',
  NIO: 'Córdoba Oro',
  NOK: 'Corona noruega',
  NPR: 'Rupia nepalí',
  NZD: 'Dólar de Nueva Zelanda',
  OMR: 'Rial omaní',
  PAB: 'Balboa',
  PEN: 'Nuevo Sol',
  PGK: 'Kina',
  PHP: 'Peso filipino',
  PKR: 'Rupia de Pakistán',
  PLN: 'Zloty',
  PYG: 'Guaraní',
  QAR: 'Qatar Rial',
  RON: 'Leu rumano',
  RSD: 'Dinar serbio',
  RUB: 'Rublo ruso',
  RWF: 'Franco ruandés',
  SAR: 'Riyal saudí',
  SBD: 'Dólar de las Islas Salomón',
  SCR: 'Rupia de Seychelles',
  SDG: 'Libra sudanesa',
  SEK: 'Corona sueca',
  SGD: 'Dolar De Singapur',
  SHP: 'Libra de Santa Helena',
  SLL: 'Leona',
  SOS: 'Chelín somalí',
  SRD: 'Dólar de Suriname',
  SSP: 'Libra sudanesa Sur',
  STD: 'Dobra',
  SVC: 'Colon El Salvador',
  SYP: 'Libra Siria',
  SZL: 'Lilangeni',
  THB: 'Baht',
  TJS: 'Somoni',
  TMT: 'Turkmenistán nuevo manat',
  TND: 'Dinar tunecino',
  TOP: "Pa'anga",
  TRY: 'Lira turca',
  TTD: 'Dólar de Trinidad y Tobago',
  TWD: 'Nuevo dólar de Taiwán',
  TZS: 'Shilling tanzano',
  UAH: 'Hryvnia',
  UGX: 'Shilling de Uganda',
  USD: 'Dolar americano',
  USN: 'Dólar estadounidense (día siguiente',
  UYI: 'Peso Uruguay en Unidades Indexadas (URUIURUI',
  UYU: 'Peso Uruguayo',
  UZS: 'Uzbekistán Sum',
  VEF: 'Bolívar',
  VND: 'Dong',
  VUV: 'Vatu',
  WST: 'Tala',
  XAF: 'Franco CFA BEAC',
  XAG: 'Plata',
  XAU: 'Oro',
  XBA: 'Unidad de Mercados de Bonos Unidad Europea Composite (EURCO',
  XBB: 'Unidad Monetaria de Bonos de Mercados Unidad Europea (UEM-6',
  XBC: 'Mercados de Bonos Unidad Europea unidad de cuenta a 9 (UCE-9',
  XBD: 'Mercados de Bonos Unidad Europea unidad de cuenta a 17 (UCE-17',
  XCD: 'Dólar del Caribe Oriental',
  XDR: 'DEG (Derechos Especiales de Giro',
  XOF: 'Franco CFA BCEAO',
  XPD: 'Paladio',
  XPF: 'Franco CFP',
  XPT: 'Platino',
  XSU: 'Sucre',
  XTS: 'Códigos reservados específicamente para propósitos de prueba',
  XUA: 'Unidad ADB de Cuenta',
  XXX:
    'Los códigos asignados para las transacciones en que intervenga ninguna moneda',
  YER: 'Rial yemení',
  ZAR: 'Rand',
  ZMW: 'Kwacha zambiano',
  ZWL: 'Zimbabwe Dólar',
};

export const categoriasProductos = {
  1: 'Hardware',
  2: 'Software',
  3: 'Computadoras',
  4: 'Impresión y Copiado',
  5: 'Audio y Video',
  6: 'Energia',
  7: 'Seguridad y Vigilancia',
  8: 'Servicios',
  9: 'Comunicación',
  10: 'Hogar',
  11: 'Home Office',
  12: 'Redes',
  13: 'Gamer',
  14: 'Disco Duro',
  15: 'SSD',
  16: 'Memoria Ram y Flash',
  17: 'Monitores',
  18: 'Discos Opticos',
  19: 'Audifonos',
  21: 'Servidores',
  22: 'Cables',
  23: 'Tarjeta de Video',
  24: 'Tarjeta Madre',
  25: 'Procesador',
  26: 'Fuente de Poder',
  27: 'Gabinete',
  28: 'Teclado',
  29: 'Memoria USB',
  30: 'Disco Duro Externo',
  31: 'Mochilas',
  32: 'Impresoras',
  33: 'Multifuncionales',
  34: 'Tóner',
  35: 'Cartuchos de Impresora',
  36: 'Tanques de Tinta',
  37: 'Pantallas',
  38: 'Bocinas',
  39: 'Proyectores',
  40: 'Cámaras Digitales',
  41: 'Cámaras y Sistemas de Vigilancia',
  42: 'Sistemas de Alarma',
  43: 'Control de Acceso',
  44: 'Sistemas Operativos',
  45: 'Sistemas Operativos para Servidores',
  46: 'Office',
  47: 'Antivirus',
  48: 'Videojuegos',
  49: 'Respaldos y Utilidades',
  50: 'Libros',
  51: 'Móvil',
  52: 'Telefonía',
  53: 'Telefonía VoIP',
  54: 'Conferencias',
  55: 'Juguetes',
  56: 'Perifericos',
  57: 'Almacenamiento',
  58: 'Quemadores de DVD',
  59: 'Lectores de DVD',
  60: 'Quemadores de Blu-ray',
  61: 'Cable de Red',
  62: 'Adaptador de Video',
  63: 'Adaptador Audio',
  64: 'Adaptador PC',
  65: 'Repetidopres',
  66: 'Router',
  67: 'Switches',
  68: 'Access Point',
  69: 'WI-FI',
  70: 'Extensor WIFI',
  71: 'Kit Teclado y Mouse',
  72: 'Joysticks',
};
